### ISSUE TITLE
Inventory scripts missing as object

### ISSUE THREAD

**Issue by ericzolf** [redhat-cop/automate_tower_genie_collections#102]
Neither in the awx.awx collection nor in this collection have I seen how to create an inventory script.

**Comment by kedark3** [comment]
@ericzolf I think we will need an issue on awx for this first. Do you mind opening one there? Or if you have, please link it here. Thanks.

**Comment by sean-m-sullivan** [comment]
@ericzolf I talked previously with the tower engineers about this. Inventory scripts are depreciated, they believe you should be using an inventory source pointed at an scm like github/gitlab with the source script/project option. Because of this, they will not be creating an inventory script module.
