### ISSUE TITLE
Treat empty strings as unset?

### ISSUE THREAD

**Issue by DWSR** [redhat-cop/automate_tower_genie_collections#141]
Came up in the discussion around #132, should empty strings (i.e. `""`) be omitted (or use the default value) when passed to modules in some or all cases?

As a consumer of this collection, there's a couple of spots where I think an intentional empty string is a "valid" value (e.g. descriptions), but most of the time I suspect an empty string will be unintentional, especially when used for credentials or connection info.

**Comment by sean-m-sullivan** [comment]
I definitly can see this for the tower host/username/password. And as you said description makes sense, Extra vars, surveys, and other fields that could stay the same if not overwritten with "" should use the default, omit/true like the username/password/host. 

The more I look at it, I agree with you on the better way of doing things, just was working on another PR, and other things, so just dont have the bandwidth atm to do it. However we should probably fix it before the next version, as it should be a larger version change due to the removal of awx.awx. prefixes

**Comment by sean-m-sullivan** [comment]
Another person came up with an issue where tower export has strings as "" or null, and believe this can fix it, will do some testing, but in that case things like Inventory, extra vars, and a host of other vars that have omit should have this, Not just user/pass

**Comment by Tompage1994** [comment]
@sean-m-sullivan this can presumably be closed now?

**Comment by sean-m-sullivan** [comment]
Yes.
