### ISSUE TITLE
settings prints passwords

### ISSUE THREAD

**Issue by ikke-t** [redhat-cop/automate_tower_genie_collections#275]
I configure LDAP to controller, and I would not want it to print the password in log.

```
TASK [redhat_cop.controller_configuration.settings : Update Ansible Controller Settings from dictionary or list of dictionaries] ************************************************
Thursday 24 February 2022  15:51:55 +0200 (0:00:00.032)       0:00:01.018 ***** 
changed: [localhost] => (item={'settings': {'AUTH_LDAP_BIND_PASSWORD': 'xxxxxx', 'AUTH_LDAP_SERVER_URI': 'ldaps://
```...

**Comment by djdanielsson** [comment]
Thanks for pointing this out, since everyone doesn't use LDAP when configuring settings I don't think we want to just blanket no_log default settings. So we might want to check if AUTH_LDAP_BIND_PASSWORD is defined and if so then set no_log or we leave it as it is and make a note in the readme that if you are setting AUTH_LDAP_BIND_PASSWORD you will want to change no_log true.

**Comment by sean-m-sullivan** [comment]
specifically you should set the variable
controller_configuration_settings_secure_logging
to True, it is default to false, there are variables similarly named for each role to turn on and off no log.

**Comment by djdanielsson** [comment]
After having re-read the readme I am not sure where a better place to point out controller_configuration_settings_secure_logging to enable no_log. If you have any suggestions on how to make this better please let us know by re-opening this issue or submitting a PR with the suggested update.
