### ISSUE TITLE
Shouldn't role `filetree_read` read all confs in `common` folder then loop on {{ env }} list, giving more freedom to end-user on structure?

### ISSUE THREAD

**Issue by nodje** [redhat-cop/automate_tower_genie_collections#394]
See
https://github.com/redhat-cop/controller_configuration/blob/a689549cd9336eb6d57922204d8147e31de26673/roles/filetree_read/defaults/main.yml#L40

value is `filetree_controller_credentials: "{{ dir_orgs_vars }}/{{ orgs }}/env/{{ env }}/controller_credentials.d/"` and I believe should be `filetree_controller_credentials: "{{ dir_orgs_vars }}/{{ orgs }}/env/common/controller_credentials.d/"`

I haven't done a MR since there are a few other settings that are read from the `{{ env }}` instead of `common`, which makes me ensure.
Is it intentional?
If so, I don't see the rational, whichever object could be common to multiple env, irrespective of what it is (settings, credentials, etc.)

**Comment by nodje** [comment]
ok, I get the logic now: `common` is planned for objects that are supposedly different accross environments.

I took `common` as a way to merge object configurations that were common to all environements, and thought ` common` folder structure would be read entirely first, then a loop would be performed on all `{{ env }}` values, leaving the end-user choose where to place things.

I believe the choice should be left to the end-user.
Imposing some object types as `common` feels very restrictive.

Why should I have to duplicate conf for objects that are identical accross environments but not read in common?

In any case, I haven't stumble upon anything regarding this in the documentation.
But yes, I don't read it top to bottom, and go straight accross.

**Comment by adonisgarciac** [comment]
Hi @nodje, credentials usually are different between environments so they should be in env folder and not in common. 

Common is defined for objects which they will be exactly the same between all environments.

Anyway, we already leave this decision to end-user because filetree_controller_credentials and rest of variables are defaults for the role. It means that they have the low power in ansible vars hierarchy. You can change paths for every object defining its own variable in your playbook. 
https://github.com/redhat-cop/controller_configuration/blob/a689549cd9336eb6d57922204d8147e31de26673/roles/filetree_read/defaults/main.yml#L40

For example, here: https://github.com/redhat-cop/controller_configuration/blob/a689549cd9336eb6d57922204d8147e31de26673/roles/object_diff/tests/drop_diff.yml#L40 we change the behavior of default controller_configuration_dispatcher_roles variable of dispatch role. This is a similar situation that you are telling.

**Comment by nodje** [comment]
Hi @adonisgarciac ,

thanks for your answers.
Though I'm not sure I understand what you mean.

I can override defaults.yml variables so as to pick credentials from the common hierarchy, e.g.:
`filetree_controller_credentials: "{{ dir_orgs_vars }}/{{ orgs }}/env/common/controller_credentials.d/"

But then nothing will be picked from the `{{ env }}` hierarchy anymore.

Is there a way to change the "lifecycle" of configs that are read ?
What I initially thought it was doing and what I'm hoping to achieve now is:
- read all object configs from `{{ dir_orgs_vars }}/{{ orgs }}/env/common`
- then read all object configs from `{{ dir_orgs_vars }}/{{ orgs }}/env/{{ env}}` and thus override anything set in the  common hierarchy.

**Comment by adonisgarciac** [comment]
Hi @nodje

You can override default location of every kind of object. For example, default path to read controller_credentials is  filetree_controller_credentials: "{{ dir_orgs_vars }}/{{ orgs }}/env/{{ env }}/controller_credentials.d/"  but if you change it for  filetree_controller_credentials: "{{ dir_orgs_vars }}/{{ orgs }}/env/common/controller_credentials.d/", credentials will be read from common. It doesn't mean that every object will be placed in common, it only means that you change location for credentials and it will be in common. Rest of object keep the default path if you don't override them.

About your question, we don't think in common as a default definition of your objects, we think in common as common objects in every env that you have. You can achieve that solution but doing it out of the role filetree_read. I mean, you can have the playbook which will manage the Configuration as Code and this playbook look for overrides paths inside {{ env }} and then override the variable filetree_controller_credentials in the playbook itslef if there is credentials in env directories.

**Comment by nodje** [comment]
thanks, I'll try something along these lines.
