### ISSUE TITLE
Dispatch role: could execution_environment be processed BEFORE inventory_sources? 

### ISSUE THREAD

**Issue by nodje** [redhat-cop/automate_tower_genie_collections#418]
I'm using v2.1.8

I've stumbled on an issue while coding an Inventory Source using and an Execution Environment that the Inventoyry Source depends on.
The Inventory Source creation fails with `"msg": "Request to /api/v2/execution_environments/?name=New+EE returned 0 items`, and rightly so because EE hasn't been processed yet.

AFAIK the order in which it is done is in roles/dispatch/defaults/main.yml.
Though examples/automatetheautomation folder contains the same case where Inventory Source depends on an EE that should be created beforehand.

**Comment by sean-m-sullivan** [comment]
These are chicken and the egg issues that come up with Execution Environments Can be assigned to orgs, and Orgs can be assigned Execution environments, or that Credentials can be in orgs and orgs can have galaxy credentials, there is currently a variable to skip that CAN make it so you are running all 3 at different orders. 

With this in mind the dispatch role is meant to be a use case that works in most cases, but could then be customized by overwriting the role's default variables to do it in another order, or with less items, and accommodate a variety of use cases. 

We do not expect this collection to be a monolith with only 1 solution on how to do things. These are tools so that you can then use them in a variety of ways that fit what you want to do.
