### ISSUE TITLE
Using object_diff with an AAP2/Tower credential without ' controller_oauthtoken' 

### ISSUE THREAD

**Issue by nodje** [redhat-cop/automate_tower_genie_collections#470]
As mentioned in previous Issues I'm starting using object_diff role now that my filetree_read/dispatch workflow is stable.

It works well in test mode when I run it with a local controller_oauthtoken, but when I commit and the webhook triggers the playbook, object_diff tasks fail because they need a `controller_validate_certs` or a  `controller_oauthtoken`, which are not required for other roles (filetree*, dispatch).

Is there any reason to force the usage of a token?

**Comment by adonisgarciac** [comment]
Yes, it is because it will do calls to the API. Example:

https://github.com/redhat-cop/controller_configuration/blob/devel/roles/object_diff/tasks/job_templates.yml#L6

If you are using the object_diff from the tower/controller, maybe you can set something like that in your playbook/variables:

https://github.com/redhat-cop/controller_configuration/blob/devel/roles/object_diff/tests/drop_diff.yml#L6-L33

**Comment by nodje** [comment]
Hi, 

thanks again for your prompt answer.

As a matter of fact the `dispatch` role is also using API calls behind the scene, as ` ansible.controller`  collection is all API calls.

But I gather you needed a specific implementation (done in lookup plugin controller_object_diff.py) to be able to achieve object difference calcultation, as this feature was not offered by the 'standard' ansible.controller collection.
Unifying how auth is done accross these two collections would probably be difficult.

I'll use the examples and tests provided in the role. 
Anyway, I need to transition from direct Webhook to Tower, to a proper CI pipeline with manual validation before applying to more sensible environments. And this will have to use token based auth.
