### ISSUE TITLE
How to install AAP2.4 using automation

### ISSUE THREAD

**Issue by Srikanth1992** [redhat-cop/automate_tower_genie_collections#779]
Hello Team

Currently, our organization runs Ansible Automation Platform (AAP) version 2.4 on RHEL 8. We have a setup with 4 nodes, including 3 HA nodes and 1 database node managed by a controller. This setup was manually done on AWS. Now, we’re considering setting up new AAP environments using Terraform and also want to handle data restoration. I’m searching for existing Terraform modules to facilitate this transition. Our aim is to fully automate the setup process.

Can anyone please share any references materials I can use to move forward.

**Comment by djdanielsson** [comment]
This is not the correct place for this, this is about managing your controllers configuration with code. while there is a collection connected to deploying AAP with Ansible (aap_utilities) we do not have any terraform related content. If I misunderstood your request let me know and reopen this but I am closing due to it not seeming to be related to this repository's content or purpose.

**Comment by sean-m-sullivan** [comment]
Best place to post this would be https://forum.ansible.com/, this collection does not do with terraform, It can use exported data, but not a database level.
